pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

include("submod")
project(":submod").name = "SubMods"

include("SubMods:SmallChange")

for (final def f in file("./libs").listFiles()) {
    include(f.name)
    project(":" + f.name).projectDir = file("./libs/" + f.name)
}

rootProject.name = "FiguraExtras"
